apiVersion: v1
kind: ConfigMap
metadata:
  name: config-broker
data:
  default.topic.partitions: "10"
  default.topic.replication.factor: "3"
  #bootstrap.servers: "kafka-0.mh-lbnyvywmvwwvpcmssqgl-4c201a12d7add7c99d2b22e361c6f175-0000.us-south.containers.appdomain.cloud:9093,kafka-2.mh-lbnyvywmvwwvpcmssqgl-4c201a12d7add7c99d2b22e361c6f175-0000.us-south.containers.appdomain.cloud:9093,kafka-1.mh-lbnyvywmvwwvpcmssqgl-4c201a12d7add7c99d2b22e361c6f175-0000.us-south.containers.appdomain.cloud:9093"
  bootstrap.servers: "my-cluster-kafka-bootstrap.kafka:9095"
  auth.secret.ref.namespace: knative-eventing
  auth.secret.ref.name: strimzi-sasl-plain-secret-legacy
---

apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: broker-1
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: config-broker

---

apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: trigger-1
spec:
  broker: broker-1
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: eventdisplay