apiVersion: v1
kind: ConfigMap
metadata:
  name: config-kafka-features
  namespace: knative-eventing
  annotations:
    knative.dev/example-checksum: "f203e503"
data:
  _example: |-
    ################################
    #                              #
    #    EXAMPLE CONFIGURATION     #
    #                              #
    ################################
    # This block is not actually functional configuration,
    # but serves to illustrate the available configuration
    # options and document them in a way that is accessible
    # to users that `kubectl edit` this config map.
    #
    # These sample configuration options may be copied out of
    # this example block and unindented to be in the data block
    # to actually change the configuration.
    #
    # Controls whether the dispatcher should use the rate limiter based on the number of virtual replicas.
    # 1. Enabled: The rate limiter is applied.
    # 2. Disabled: The rate limiter is not applied.
    dispatcher.rate-limiter: "disabled"
    # Controls whether the dispatcher should record additional metrics.
    # 1. Enabled: The metrics are recorded.
    # 2. Disabled: The metrics are not recorded.
    dispatcher.new-metrics: "disabled"
  dispatcher.rate-limiter: "disabled"
  dispatcher.new-metrics: "disabled"
